### PR TITLE
Centering the nearest Node

### LINKED ISSUE #15: [GUI] Center neariest Node
After the User inputs Latitude and Longitude the map should move it's center to the nearest Node of the given input

### PR DESCRIPTION
**Pull request by ghost**
fixes #15 
Centering the nearest node was implemented.
Some issues in the GUI are now fixed.
The GUI clears now all parameters before taking a new request.

### CODE REVIEW

**Comment by PhilippCl** [comment]
This branch has conflicts with the current master. Please fix

**Comment by jonastogo** [comment]
Ich räum das nicht auf

**Comment by PhilippCl** [comment]
Also please use the functions listed on the right to notify other Developers

**Comment by Hator21** [comment]
Dennis mach den scheiß ordenlich

**Pull request merged**
